### ISSUE TITLE
I can't install the package

### ISSUE THREAD

**Issue by nereischan** [KennethTM/sonaR#2]
When I try to install the package using: 
remotes::install_github('KennethTM/sonaR')

I get the following error

ERROR: compilation failed for package 'sonaR'
* removing 'C:/RLibrary/R/library/sonaR'
* restoring previous 'C:/RLibrary/R/library/sonaR'
Warning messages:
1: In i.p(...) : installation of package ‘Rcpp’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘C:/Users/sara-g/AppData/Local/Temp/RtmpOytAti/file126456dceab/sonaR_0.0.2.tar.gz’ had non-zero exit status

Is the package working in R 4.1.2?

**Comment by KennethTM** [comment]
Hi 

I am able to install with R 4.2. Maybe the problem is installing Rcpp? This package has to be installed successfully in order to install sonaR.

Best regards,
Kenneth
